const civicImage = "/img/civic.jpg";
const hiluxImage = "/img/hilux.jpg";
const corollaImage = "/img/Toyota-Corolla-2024-trompa-1.jpg";
const fordImage = "/img/ford.jpg";
const bmwImage = "/img/bmw.jpg";
const pradoImage = "/img/prado.jpg";
const dmaxImage = "/img/D-max.jpg";

export const demoCars = [
  {
    id: "honda-civic",
    name: "Civic",
    brand: "Honda",
    origin: "Japan",
    year_range: "2016-2021",
    engine: "2.0L i-VTEC",
    horsepower: 158,
    torque: "138 lb-ft",
    drivetrain: "FWD",
    image_url: civicImage,
    description: "Sedan confiable y popular para proyectos visuales y street build.",
    is_featured: true,
  },
  {
    id: "toyota-corolla",
    name: "Corolla",
    brand: "Toyota",
    origin: "Japan",
    year_range: "2017-2023",
    engine: "1.8L Dual VVT-i",
    horsepower: 139,
    torque: "126 lb-ft",
    drivetrain: "FWD",
    image_url: corollaImage,
    description: "Base versatil para estilo diario, suspension y mejoras ligeras.",
    is_featured: true,
  },
  {
    id: "ford-focus-st",
    name: "Focus ST",
    brand: "Ford",
    origin: "USA",
    year_range: "2013-2018",
    engine: "2.0L EcoBoost",
    horsepower: 252,
    torque: "270 lb-ft",
    drivetrain: "FWD",
    image_url: fordImage,
    description: "Hot hatch con gran potencial para manejo deportivo y potencia.",
    is_featured: true,
  },
  {
    id: "bmw-series-3",
    name: "Series 3",
    brand: "BMW",
    origin: "Germany",
    year_range: "2016-2022",
    engine: "2.0L TwinPower Turbo",
    horsepower: 255,
    torque: "295 lb-ft",
    drivetrain: "RWD",
    image_url: bmwImage,
    description: "Sedan premium con buen equilibrio entre lujo y performance.",
    is_featured: false,
  },
  {
    id: "toyota-hilux",
    name: "Hilux",
    brand: "Toyota",
    origin: "Japan",
    year_range: "2021-2024",
    engine: "2.8L Turbo Diesel",
    horsepower: 201,
    torque: "369 lb-ft",
    drivetrain: "4WD",
    image_url: hiluxImage,
    description: "Pickup robusta ideal para setup off-road y presencia agresiva.",
    is_featured: false,
  },
  {
    id: "toyota-prado",
    name: "Prado",
    brand: "Toyota",
    origin: "Japan",
    year_range: "2020-2024",
    engine: "2.8L Turbo Diesel",
    horsepower: 201,
    torque: "369 lb-ft",
    drivetrain: "4WD",
    image_url: pradoImage,
    description: "SUV fuerte y elegante para proyecto familiar, premium y aventurero.",
    is_featured: false,
  },
  {
    id: "isuzu-dmax",
    name: "D-Max",
    brand: "Isuzu",
    origin: "Japan",
    year_range: "2021-2024",
    engine: "3.0L Turbo Diesel",
    horsepower: 188,
    torque: "332 lb-ft",
    drivetrain: "4WD",
    image_url: dmaxImage,
    description: "Pickup de trabajo y aventura con look solido para personalizar.",
    is_featured: false,
  },
];

export const demoModifications = [
  {
    id: "mod-civic-1",
    car_id: "honda-civic",
    name: "Lowering Springs Kit",
    category: "Stance",
    description: "Mejora altura y presencia sin perder comodidad diaria.",
    difficulty: "Bolt-On",
    price_range: "$300 - $650",
  },
  {
    id: "mod-civic-2",
    car_id: "honda-civic",
    name: "Cold Air Intake",
    category: "Power",
    description: "Respuesta mas libre y sonido deportivo.",
    power_gain: "+8 HP",
    difficulty: "Bolt-On",
    price_range: "$250 - $500",
  },
  {
    id: "mod-corolla-1",
    car_id: "toyota-corolla",
    name: "Front Lip + Side Skirts",
    category: "Aero",
    description: "Paquete visual para darle una presencia mas deportiva.",
    difficulty: "Moderate",
    price_range: "$450 - $900",
  },
  {
    id: "mod-corolla-2",
    car_id: "toyota-corolla",
    name: "Cat-Back Exhaust",
    category: "Exhaust",
    description: "Sonido mas limpio y un look trasero mas agresivo.",
    difficulty: "Bolt-On",
    price_range: "$500 - $1,000",
  },
  {
    id: "mod-focus-1",
    car_id: "ford-focus-st",
    name: "Stage 2 ECU Tune",
    category: "Electronics",
    description: "Ajuste de mapa para mejorar torque y respuesta.",
    power_gain: "+40 HP",
    difficulty: "Moderate",
    price_range: "$700 - $1,200",
  },
  {
    id: "mod-focus-2",
    car_id: "ford-focus-st",
    name: "Big Brake Upgrade",
    category: "Brakes",
    description: "Frenado mas consistente para uso dinamico.",
    difficulty: "Advanced",
    price_range: "$1,500 - $2,800",
  },
  {
    id: "mod-bmw-1",
    car_id: "bmw-series-3",
    name: "Coilover Suspension",
    category: "Stance",
    description: "Setup ajustable para lograr una postura mas limpia y firme.",
    difficulty: "Advanced",
    price_range: "$1,200 - $2,500",
  },
  {
    id: "mod-bmw-2",
    car_id: "bmw-series-3",
    name: "M Performance Body Kit",
    category: "Aero",
    description: "Detalles visuales premium para reforzar la identidad deportiva.",
    difficulty: "Moderate",
    price_range: "$1,000 - $2,200",
  },
  {
    id: "mod-hilux-1",
    car_id: "toyota-hilux",
    name: "Lift Kit + Off-Road Tires",
    category: "Stance",
    description: "Mayor altura y traccion para un look aventurero.",
    difficulty: "Advanced",
    price_range: "$1,800 - $3,500",
  },
  {
    id: "mod-prado-1",
    car_id: "toyota-prado",
    name: "Roof Rack + Utility Setup",
    category: "Aero",
    description: "Configuracion practica y visual para viaje y aventura.",
    difficulty: "Moderate",
    price_range: "$700 - $1,400",
  },
  {
    id: "mod-dmax-1",
    car_id: "isuzu-dmax",
    name: "All Terrain Wheel Package",
    category: "Stance",
    description: "Rines y llantas para reforzar presencia y capacidad.",
    difficulty: "Bolt-On",
    price_range: "$1,200 - $2,100",
  },
];

export function buildModCounts(mods) {
  return mods.reduce((counts, mod) => {
    counts[mod.car_id] = (counts[mod.car_id] || 0) + 1;
    return counts;
  }, {});
}
